version: "3"
services:
  ghost:
    container_name: blog-ghost
    image: ghost:latest
    ports:
      - 10005:2368
    restart: always
    privileged: true
    depends_on:
      - db
    environment:
      url: https://blog.koder.page
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${MYSQL}
      database__connection__database: ghost
    volumes:
      - ghost:/var/lib/ghost/content

  db:
    container_name: blog-db
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL}
    volumes:
      - ghost-db:/var/lib/mysql

volumes:
  ghost:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/ghost"
  ghost-db:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/ghost-db"
