version: "3"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${PASSWORD}
      - PROXY_DOMAIN=${URL}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - code-server:/config
    ports:
      - 8443:8443
      - 27121:27121
    restart: unless-stopped

volumes:
  code-server:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/code-server"
