version: "3"
services:
  gonic:
    container_name: gonic
    privileged: true
    image: sentriz/gonic:latest
    ports:
      - 4747:80
    restart: always
    environment:
      GONIC_EXCLUDE_PATTERN: "@eadir"
    volumes:
      - playlists:/playlists
      - data:/data
      - music:/music
      - podcasts:/podcasts

volumes:
  playlists:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/gonic/playlists"
  podcasts:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/gonic/podcasts"
  data:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/gonic/data"
  music:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume2/02_Media/Music"
