version: "3"
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-create
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_SLUG: just-create-smp
      CF_API_KEY: ${CF_API_KEY}
      MAX_MEMORY: "8G"
      SEED: "-4685302507262399715"
      UID: 0
      GID: 0
    volumes:
      - minecraft-create:/data
volumes:
  minecraft-create:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,nfsvers=4,rw"
      device: ":/volume1/01_Docker/minecraft-create"
