version: "3"

services:
  web:
    image: misskey/misskey:latest
    container_name: misskey
    # restart: always
    user: 0:0
    links:
      - db
      - redis
    # - meilisearch
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - internal_network
      - external_network
    volumes:
      - files:/misskey/files
      - config:/misskey/.config:ro

  redis:
    container_name: misskey-redis
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    container_name: misskey-db
    restart: always
    image: postgres:15-alpine
    env_file:
      - stack.env
    networks:
      - internal_network
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

networks:
  internal_network:
    internal: true
  external_network:

volumes:
  files:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/misskey/files"
  config:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/misskey/config"
  db-volume:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/misskey/db"
  redis:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/misskey/redis"
