version: "3.9"
services:
  obsidian-db:
    image: couchdb
    container_name: obsidian-db
    environment:
      - COUCHDB_USER=${user} # <- 여기에 아이디
      - COUCHDB_PASSWORD=${pass} # <- 여기에 비밀번호
    volumes:
      - db:/opt/couchdb/data # 본인 디렉토리
      - ini:/opt/couchdb/etc/local.d/
    ports:
      - 5984:5984
    restart: unless-stopped
volumes:
  db:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/obsidian-db/data"
  ini:
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,vers=4.1,rw"
      device: ":/volume1/01_Docker/obsidian-db/config"
