version: "3.1"

services:
  mysql:
    container_name: dev-db
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      TZ: Asia/Seoul
    volumes:
      - /volume1/01_Docker/dev-db:/var/lib/mysql
